### ISSUE TITLE
Broken link on the npmjs.com

### ISSUE THREAD

**Issue by ptretyakov** [unional/typescript-guidebook#17]
Aloha! :-)
You have renamed the repo and currently, links on https://www.npmjs.com/package/typescript-style are not working. It's not a issue, but it's a little note - your npm package had topic position on google queries ))

**Comment by unional** [comment]
Thanks for letting me know about this. 🌷 

Now this repo contains only guidelines, so maybe removing it from npm is the more reasonable approach. :)
